draft: feat: add project list section in home page
divyanshugarg36/brl-cad-web pull request #21
Opened 2022-07-09 19:42 UTC by divyanshugarg36

Add a project list on the home page showing 2 projects in the beginning

2022-07-15 08:27 UTC, theamanjs requested changes

2022-07-15 08:27 UTC, theamanjs commented on src/components/ProjectSection.tsx
> +  ];
Can this be moved to another constant file?

2022-07-15 08:27 UTC, theamanjs commented on src/components/common/ProjectCard.tsx
> +      <a>Visit Github</a>
Should this string come from i18n?

2022-07-16 20:30 UTC, divyanshugarg36 commented on src/components/ProjectSection.tsx
> +  ];
This has been fixed

2022-07-16 20:31 UTC, divyanshugarg36 commented on src/components/common/ProjectCard.tsx
> +      <a>Visit Github</a>
Moved to i18n

2022-07-19 11:40 UTC, theamanjs commented on src/components/common/ProjectCard.tsx
> +      <a>Visit Github</a>
coool

2022-07-19 11:40 UTC, theamanjs approved these changes

2022-07-19 12:08 UTC, merged